In [49]:
import pandas as pd
from plotnine import *
from plotnine.data import mpg
from plotnine.data import mtcars
%matplotlib inline

df_desm = pd.read_csv('../dados/desmatamento_ucs_atualizado_2021.csv', sep=';')

df_incen = pd.read_csv('../dados/incendios_em_unidades_de_conservacao_federal.csv', sep='\t')

df_lim_uc = pd.read_csv('../dados/Limite_UC_federais_jun_2021_CSV.csv', sep=';')

In [50]:
df_desm

,Cód. CNUC,uc,biocgfun,prodes,2021,2020,2019,2018,2017,2016,...,2008,2007,2006,2005,2004,2003,2002,2001,2000,1997
0,0000.00.0001,APA Anhatomirim,Marinho-Costeiro,Não,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0000.00.0002,APA Cavernas do Peruaçu,Cerrado,Sim,"41,8698","25,9009","8,686","27,0174","90,3144","15,5474",...,"127,8657","127,8657","1455,18475","1455,18475","1442,04345","1442,04345","823,97995","823,97995","7048,5908",0
2,0000.00.0003,APA da Bacia do Rio Descoberto,Cerrado,Sim,"29,4815","16,9189","6,1382","34,8262","47,261","27,5458",...,"60,666","60,666","133,0672","133,0672","424,46005","424,46005","35,2013","35,2013","24411,3688",0
3,0000.00.0004,APA da Bacia do Rio São Bartolomeu,Cerrado,Sim,"81,5854","75,1749","80,5036","185,9016","65,1662","32,8627",...,"114,38775","114,38775","521,3432","521,3432","1970,2341","1970,2341","110,89395","110,89395","40247,2264",0
4,0000.00.0005,APA da Bacia do Rio São João - Mico-Leão-Dourado,Mata Atlântica,Não,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,0000.00.3410,PARNA do Acari,Amazônia,Sim,"8,0403","193,3631","3,835","7,3076","14,0984",0,...,0,0,0,0,0,0,0,0,0,0
321,0000.00.3411,REBIO do Manicoré,Amazônia,Sim,"21,3202","6,4048",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
322,0000.00.3432,REVIS do Arquipélago de Alcatrazes,Marinho-Costeiro,Não,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
323,0000.00.3519,PARNA dos Campos Ferruginosos,Amazônia,Sim,"1,9271",0,"197,0321","26,8094","13,1762","105,0862",...,0,0,0,0,0,0,0,0,0,0
324,0000.00.3693,RESEX Baixo Rio Branco-Jauaperi,Amazônia,Sim,"14,33",0,0,"7,1987",0,0,...,0,0,0,0,0,0,0,0,0,0

In [51]:
df_incen

,Cód. CNUC,UC,AAF,ANO,Unnamed: 4
0,0000.00.0168,PARNA do Araguaia,"277.808,40",2012,NaN
1,0000.00.0076,ESEC Serra Geral do Tocantins,"251.539,10",2012,NaN
2,0000.00.0156,PARNA das Nascentes do Rio Parnaíba,"153.878,60",2012,NaN
3,0000.00.0144,PARNA da Serra da Canastra,"88.365,50",2012,NaN
4,0000.00.0024,APA Meandros do Araguaia,"82.626,40",2012,NaN
...,...,...,...,...,...
358,0000.00.1907,REVIS de Boa Nova,"76,2",2019,NaN
359,0000.00.3136,PARNA da Serra do Gandarela,"140,8",2019,NaN
360,0000.00.3409,FLONA do Aripuanã,"100,5",2019,NaN
361,0000.00.3410,PARNA do Acari,445,2019,NaN
362,0000.00.3519,PARNA dos Campos Ferruginosos,"1.354,40",2019,NaN

In [53]:
df_lim_uc.sort_values(by=["Cód. CNUC"])

,Cód. CNUC,Nome da UC,Categoria,Coord. Regional,Ano/Criação,Área (hect),Perimetro (m),Ato legal,Grupo,UF,Municípios,Bioma,Fuso/abrangencia
0,0000.00.0001,ÁREA DE PROTEÇÃO AMBIENTAL ANHATOMIRIM,APA,GR 5- SUL,1992,"4.436,59","36.563,46",DEC 528 de 20/05/1992,US,SC,Governador Celso Ramos.,MATA ATLÂNTICA,22S
3,0000.00.0002,ÁREA DE PROTEÇÃO AMBIENTAL CAVERNAS DO PERUAÇU,APA,GR 4- SUDESTE,1989,"143.355,59","225.638,81",DEC 98.182 de 26/09/1989,US,MG,"Bonito de Minas, Cônego Marinho, Januária, Ita...",CERRADO,23S
6,0000.00.0003,ÁREA DE PROTEÇÃO AMBIENTAL DA BACIA DO RIO DES...,APA,GR 3 - CENTRO-OESTE,1983,"41.783,61","93.435,20",DEC 88.940 de 07/11/1983,US,GO/DF,"Brasília, Águas Lindas de Goiás, Padre Bernardo.",CERRADO,22S
7,0000.00.0004,ÁREA DE PROTEÇÃO AMBIENTAL DA BACIA DO RIO SÃO...,APA,GR 3 - CENTRO-OESTE,1983,"82.680,80","176.700,71",DEC 88.940 de 07/11/1983,US,DF,Brasília.,CERRADO,23S
8,0000.00.0005,ÁREA DE PROTEÇÃO AMBIENTAL DA BACIA DO RIO SÃO...,APA,GR 4- SUDESTE,2002,"150.374,61","369.887,78",DEC S/N de 27/06/2002,US,RJ,"Silva Jardim, Cachoeiras de Macacu, Rio Bonito...",MATA ATLÂNTICA,23S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,0000.00.3654,RESERVA EXTRATIVISTA ARAPIRANGA-TROMAÍ,RESEX,GR 1 - NORTE,2018,"186.909,14","196.671,28",DEC 9.339 de 05/04/2018,US,MA,Carutapera e Luís Domingues.,MARINHO COSTEIRO,23S
26,0000.00.3655,ÁREA DE PROTEÇÃO AMBIENTAL DO BOQUEIRÃO DA ONÇA,APA,GR 2- NORDESTE,2018,"505.694,33","606.137,97",DEC 9.337 de 05/04/2018,US,BA,"Sento Sé, Juazeiro, Sobradinho, Campo Formoso,...",CAATINGA,24S
273,0000.00.3693,RESERVA EXTRATIVISTA BAIXO RIO BRANCO-JAUAPERI,RESEX,GR 1 - NORTE,2018,"580.630,92","511.439,91",DEC 9.401 de 05/06/2018,US,AM/RR,"Novo Airão, Rorainópolis.",AMAZÔNIA,20N
226,0000.00.3694,REFÚGIO DE VIDA SILVESTRE DA ARARINHA AZUL,REVIS,GR 2- NORDESTE,2018,"29.234,73","109.426,87",DEC 9.402 de 05/06/2018,PI,BA,"Juazeiro, Curuçá.",CAATINGA,24S
5,0000.00.3696,ÁREA DE PROTEÇÃO AMBIENTAL DA ARARINHA AZUL,REVIS,GR 2- NORDESTE,2018,"90.641,92","271.274,25",DEC 9.402 de 05/06/2018,US,BA,"Juazeiro, Curuçá.",CAATINGA,24S

In [47]:
df_incen2 = df_incen.copy()
df_incen2

df_incen2.drop(["Unnamed: 4"], axis=1, inplace=True)

df_incen2

        Cód. CNUC                                   UC         AAF   ANO
0    0000.00.0168                    PARNA do Araguaia  277.808,40  2012
1    0000.00.0076        ESEC Serra Geral do Tocantins  251.539,10  2012
2    0000.00.0156  PARNA das Nascentes do Rio Parnaíba  153.878,60  2012
3    0000.00.0144           PARNA da Serra da Canastra   88.365,50  2012
4    0000.00.0024             APA Meandros do Araguaia   82.626,40  2012
..            ...                                  ...         ...   ...
358  0000.00.1907                    REVIS de Boa Nova        76,2  2019
359  0000.00.3136          PARNA da Serra do Gandarela       140,8  2019
360  0000.00.3409                    FLONA do Aripuanã       100,5  2019
361  0000.00.3410                       PARNA do Acari         445  2019
362  0000.00.3519        PARNA dos Campos Ferruginosos    1.354,40  2019

[363 rows x 4 columns]

In [48]:
df_incen2.sort_values(by=['Cód. CNUC'])

        Cód. CNUC                                  UC       AAF   ANO
222  0000.00.0002             APA Cavernas do Peruaçu     260,7  2017
240  0000.00.0003      APA da Bacia do Rio Descoberto  1.585,40  2017
241  0000.00.0004  APA da Bacia do Rio São Bartolomeu  1.620,00  2017
246  0000.00.0011            APA Serra da Mantiqueira  3.703,60  2017
238  0000.00.0019               APA Delta do Parnaíba  1.367,10  2017
..            ...                                 ...       ...   ...
361  0000.00.3410                      PARNA do Acari       445  2019
289  0000.00.3411                   REBIO do Manicoré     716,7  2018
254  0000.00.3519       PARNA dos Campos Ferruginosos  7.173,10  2017
362  0000.00.3519       PARNA dos Campos Ferruginosos  1.354,40  2019
298  0000.00.3652          PARNA do Boqueirao da Onça  3.224,40  2018

[363 rows x 4 columns]